language: node_js
node_js:
  - 8.9

before_install:
  - npm install -g gulp

script:
  - gulp

after_script:
  - gulp coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage